exportDir: /Users/ebolton/Documents/kindle-clippings/exports
ignorable:
  - The Moneyless Man (Mark Boyle)
  - The Secret Thoughts of an Unlikely Convert (Rosaria Butterfield)
  - The Holy Bible, English Standard Version (Crossway Bibles)
  - Deliver Us From Me-Ville (David Zimmerman)
